### PR TITLE
Features/cherkasy 102 implement highdim resource

### PR DESCRIPTION
**Pull request by alchimystic**

### CODE REVIEW

**Comment by alchimystic** [comment]
So, should i just pick the default DEFAULT_REAL_PROJECTION if supported, and the first/only if not?
Or just make the projection mandatory from the client?

**Comment by cataphract** [comment]
Either option would be fine by me. As long as there's no need to keep a list that you'll have to update as you add new data types.

**Comment by alchimystic** [comment]
I'm only using `AcghModule.ACGH_VALUES_PROJECTION` because that constant is not in `Projection` and i don't like to have copied strings all over the code.

**Comment by cataphract** [comment]
It's fine to copy it all over the code. It's part of the interface of the acgh data type contract; users of it are expected to know about that projection. What is not part of the client interface is any of `*Modules` classes. `Projection` doesn't have that constant because `Projection` is supposed to be data type agnostic. If someone implements a data type in separate module, he wouldn't be able to change `Projection` anyway.

If you want to avoid typing the string in several places, create a constant on the client side. Again, it's fine to hardcode it in the client because it's part of the contract of the acgh type.

**Comment by cataphract** [comment]
BTW, about the earlier comment: in the clients, use the type `HighDimensionResource`, not `HighDimensionResourceService`.

**Comment by alchimystic** [comment]
Some remarks:
- 'In general, never import anything from...' is a rule we can have in projects to forbid direct access to core-db
- tests will always have to know what to expect from data, so they need to have some knowledge about the dataType specific classes. Why to consider core-db-tests as a separate module if not for that reason?
- Later i will try to create protobuf matchers not from the TestData, but from the TabularResults. Anyway, for that i need to implement some TabularResults that is persistent (not exausted while visiting rows)

**Comment by cataphract** [comment]
- Unfortunately, I am yet to find a way to enforce that rule. Grails does not enforce compile/runtime separations on dependencies. I explorered the possibility of hooking into the groovy compiler, but I couldn't find a way without messing with the Grails scripts and their Ant targets, something I'd rather not do.
- I disagree, I don't think we need knowledge about the data expect in an abstract sense ("we have two studies, one of them has mrna data, etc.", not "there's one row in i2b2 with that value" or "there's a GORM object with this class"). The poiny of separating `core-db-tests` is to have a _RUNTIME_ environment where data and the core-db services are available, but not to depend at compile-time on those details.

**Pull request merged**
