### PR TITLE
Better marshallers

### PR DESCRIPTION
**Pull request by cataphract**
Now works the same way as in core-db. The marshallers can more easily be
tested and don't have to be added manually to a list -- instead there's
some class scanning on application startup.

This also enables pretty printing, except for production.

### CODE REVIEW

**Comment by JanKanis** [comment]
So, you are introspectively registering marshallers based on them having a magic name (ending in *Marshaller)? That seems way too much magic. How about doing that annotating them with an annotation, at least in that way someone having a look at the class knows what to grep for.

**Comment by cataphract** [comment]
@JanKanis I could of course use an annotation, but I don't see how it's fundamentally different from using the class name. In both cases we're using some metadata about the class to decide whether to pick it up on the scan. Plus, the search is limited to one package, so the potential for classes to accidentally picked up is minor.

It is true that an annotation is a bit more explicit, but I think the fact it's done the same way on core-db weights in favor of leaving it as is, as won't be doing the same thing in two different ways in the two projects.

**Comment by JanKanis** [comment]
We're also doing that in coredb? I'd argue that needs to be changed as well. The problem is that if someone is looking at such a marshaller class, there is no indication that this (magic) introspection is going on. Having an annotation at least indicates that something funny is happening and gives the programmer a clue what to look for.

**Comment by cataphract** [comment]
OK, I don't mind implementing that change.

**Pull request merged**
